FROM imione/awscli-local

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /wait
RUN chmod +x /wait

COPY ./scripts/create-s3-buckets.sh ./elife-666-vor-r1.zip ./

CMD ["./create-s3-buckets.sh"]
