FROM python:3.7.3-alpine3.9

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /wait
RUN chmod +x /wait

RUN pip install -U awscli-local

COPY create-s3-buckets.sh .

CMD ["./create-s3-buckets.sh"]
